config/routes.rb
Farm::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'

  resources :animals

  resources :incidents

  resources :breeds

  resources :stocks

  resources :activities, except: [:update]

end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  count       :integer
#  date        :datetime
#  incident_id :integer
#  breed_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Activity < ActiveRecord::Base
  belongs_to :incident
  belongs_to :breed
end

app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Animal < ActiveRecord::Base
	has_many :breeds
	validates :name, presence: true
end

app/models/breed.rb
# == Schema Information
#
# Table name: breeds
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  animal_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Breed < ActiveRecord::Base
  belongs_to :animal
  belongs_to :activity
  has_one    :stock, :dependent => :destroy
end

app/models/incident.rb
# == Schema Information
#
# Table name: incidents
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  is_addition :boolean
#

class Incident < ActiveRecord::Base
	belongs_to :activity
	validates :name, presence: true

	
end

app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  count      :integer
#  breed_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Stock < ActiveRecord::Base
  belongs_to :breed
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :set_record, only: [:show, :edit, :update, :destroy]

	def new
		@breeds = Breed.all
		@incidents = Incident.all
    @animals = Animal.all
	end

	def create
		@activity = Activity.new(activity_params)
 
  		if @activity.save
  			update_stock_record(@activity)
    		redirect_to '/stocks'
  		else
    		render 'new'
  		end
	end

	def show
	end

	def index
  		@activities = Activity.all
	end

	def edit
  		@breeds = Breed.all
		@incidents = Incident.all
	end

	def update
  		if @breed.update(breed_params)
  			create_stock_record
    		redirect_to @breed
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@activity.destroy
  		update_stock_record(@activity, true)
  		redirect_to breeds_path
	end

	private
		def set_record
  			@activity = Activity.find(params[:id])
		end

  		def activity_params
    		params.require(:activity).permit(:count, :date, :breed_id, :incident_id)
  		end

  		def update_stock_record(activity, reverse = false)
  			if stock = activity.breed.stock
  				if (activity.incident.is_addition && !reverse) || (!activity.incident.is_addition && reverse)
            stock.increment(:count, activity.count)
          else
            stock.decrement(:count, activity.count)
          end
          # Negative stocks are allowed because of untimely transactions
          stock.save
  			end
  		end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
	def new
    @animal = Animal.new
	end

	def create
  		@animal = Animal.new(animal_params)
 
  		if @animal.save
    		redirect_to @animal
  		else
    		render 'new'
  		end
	end

	def show
  		@animal = Animal.find(params[:id])
	end

	def index
  		@animals = Animal.all
	end

	def edit
  		@animal = Animal.find(params[:id])
	end

	def update
  		@animal = Animal.find(params[:id])
 
  		if @animal.update(animal_params)
    		redirect_to @animal
  		else
    	render 'edit'
  		end
	end

	def destroy
  		@animal = Animal.find(params[:id])
  		@animal.destroy
 
  		redirect_to animals_path
	end

	private
  		def animal_params
    		params.require(:animal).permit(:name, :description)
  		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
	before_action :set_record, only: [:show, :edit, :update, :destroy]

	def new
		@animals = Animal.all
	end

	def create
		@breed = Breed.new(breed_params)
 
  		if @breed.save
  			create_stock_record
    		redirect_to @breed
  		else
    		render 'new'
  		end
	end

	def show
	end

	def index
  		@breeds = Breed.all
	end

	def edit
  		@animals = Animal.all
	end

	def update
  		if @breed.update(breed_params)
  			create_stock_record
    		redirect_to @breed
  		else
    		render 'edit'
  		end
	end

	def destroy
  		@breed.destroy
 
  		redirect_to breeds_path
	end

	private
		def set_record
  			@breed = Breed.find(params[:id])
		end

  		def breed_params
    		params.require(:breed).permit(:name, :animal_id)
  		end

  		def create_stock_record
  			Stock.where(breed: @breed).first_or_create(count: 0)
  		end

end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
	def new
	end

	def create
  		@incident = Incident.new(incident_params)
 
  		if @incident.save
    		redirect_to @incident
  		else
    		render 'new'
  		end
	end

	def show
  		@incident = Incident.find(params[:id])
	end

	def index
  		@incidents = Incident.all
	end

	def edit
  		@incident = Incident.find(params[:id])
	end

	def update
  		@incident = Incident.find(params[:id])
 
  		if @incident.update(incident_params)
    		redirect_to @incident
  		else
    	render 'edit'
  		end
	end

	def destroy
  		@incident = Incident.find(params[:id])
  		@incident.destroy
 
  		redirect_to incidents_path
	end

	private
  		def incident_params
    		params.require(:incident).permit(:name, :description, :is_addition)
  		end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	def index
		@stocks = Stock.all
	end

	def show
		@stock = Stock.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/activities/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Listing Activities</h1>
        <hr>
      </div>
      <div class="col-lg-12">
      <%= link_to 'New Activity', new_activity_path %>
        <table class="table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Incident</th>
              <th>Breed</th>
              <th>Count</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.date%></td>
            <td><%= activity.incident.name %></td>
            <td><%= activity.breed.name %></td>
            <td><%= activity.count %></td>
            <td><%= link_to 'Show', activity_path(activity) %></td>
            <td><%= link_to 'Destroy', activity_path(activity),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/activities/new.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
			<h2>Add Activity</h2>
				<hr>
			</div>
			<div class="col-lg-12">
				<%= link_to 'Back', activities_path %>
				<%= form_for :activity, url: activities_path do |f| %>
				<p>
					<%= f.label 'Incident' %><br>
					<% options = options_from_collection_for_select(@incidents, 'id', 'name') %>
					<%= f.select :incident_id,  options %>
				</p>

				<p>
					<%= f.label 'Breed' %><br>
					<% options_ = options_from_collection_for_select(@breeds, 'id', 'name') %>
					<% options = option_groups_from_collection_for_select(@animals, :breeds,'name', 'id', 'name') %>
					<%= f.select :breed_id,  options %>
				</p>

				<p>
					<%= f.label 'Date' %><br>
					<%= f.date_select(:date, :order => [:day, :month, :year]) %>
				</p>

				<p>
					<%= f.label 'Count' %><br>
					<%= f.number_field :count %>
				</p>

				<p>
					<%= f.submit %>
				</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/activities/show.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h2>Listing Activities</h2>
				<hr>
			</div>
			<div class="col-lg-12">
				<%= link_to 'Back', activities_path %>
				<p>
					<strong>Date:</strong>
					<%= @activity.date %>
				</p>

				<p>
					<strong>Incident:</strong>
					<%= @activity.incident.name %>
				</p>

				<p>
					<strong>Breed:</strong>
					<%= @activity.breed.name %>
				</p>
				
				<p>
					<strong>Count:</strong>
					<%= @activity.count %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/animals/_form.html.erb
<% if @animal.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:
  </h2>
  <ul>
    <% @animal.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

app/views/animals/edit.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Editing Animal</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= form_for :animal, url: animal_path(@animal), method: :patch do |f| %>
        <%= render partial: 'form', locals: {f: f} %>
        <p>
          <%= f.submit %>
        </p>
        <% end %>
        <%= link_to 'Back', animals_path %>
      </div>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Listing Animals</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= link_to 'New animal', new_animal_path %>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          
          <% @animals.each do |animal| %>
          <tr>
            <td><%= animal.name %></td>
            <td><%= animal.description %></td>
            <td><%= link_to 'Show', animal_path(animal) %></td>
            <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
            <td><%= link_to 'Destroy', animal_path(animal),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/animals/new.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>New Animal</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= form_for @animal do |f| %>
        <%= render partial: 'form', locals: {f: f} %>
        <p>
          <%= f.submit %>
        </p>
        <% end %>
        <%= link_to 'Back', animals_path %>
      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>Animal</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<p>
					<strong>Name:</strong>
					<%= @animal.name %>
				</p>

				<p>
					<strong>Description:</strong>
					<%= @animal.description %>
				</p>
				<%= link_to 'Back', animals_path %> | <%= link_to 'Edit', edit_animal_path(@animal) %>
			</div>
		</div>
	</div>
</div>

app/views/breeds/edit.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Editing Breed</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= form_for :breed, url: breed_path(@breed), method: :patch do |f| %>
        <% if @breed.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:
          </h2>
          <ul>
            <% @breed.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <p>
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </p>
        
        <p>
          <%= f.label 'Select Animal' %><br>
          <%= f.select :animal_id, options_for_select(@animals.collect {|p| [ p.name, p.id ] }, @breed.animal_id) %>
        </p>
        
        <p>
          <%= f.submit %>
        </p>
        <% end %>
        <%= link_to 'Back', breeds_path %>
      </div>
    </div>
  </div>
</div>

app/views/breeds/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>All Breeds</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= link_to 'New Breed', new_breed_path %>
        <table class="table">
          <thead>
            <tr>
              <th>Animal</th>
              <th>Breed</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          
          <% @breeds.each do |breed| %>
          <tr>
            <td><%= breed.animal.name%></td>
            <td><%= breed.name %></td>
            <td><%= link_to 'Show', breed_path(breed) %></td>
            <td><%= link_to 'Edit', edit_breed_path(breed) %></td>
            <td><%= link_to 'Destroy', breed_path(breed),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/breeds/new.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>New Breed</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<%= form_for :breed, url: breeds_path do |f| %>
				<p>
					<%= f.label :name %><br>
					<%= f.text_field :name %>
				</p>

				<p>
					<%= f.label 'Animal' %><br>
					<% options = options_from_collection_for_select(@animals, 'id', 'name') %>
					<%= f.select :animal_id,  options %>
				</p>

				<p>
					<%= f.submit %>
				</p>
				<% end %>
				<%= link_to 'Back', breeds_path %>
			</div>
		</div>
	</div>
</div>

app/views/breeds/show.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>Breed</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<p>
					<strong>Name:</strong>
					<%= @breed.name %>
				</p>

				<p>
					<strong>Animal:</strong>
					<%= @breed.animal.name %>
				</p>
				<%= link_to 'Back', breeds_path %> | <%= link_to 'Edit', edit_breed_path(@breed) %>
			</div>
		</div>
	</div>
</div>

app/views/incidents/edit.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Editing Incident</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= form_for :incident, url: incident_path(@incident), method: :patch do |f| %>
        <% if @incident.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:
          </h2>
          <ul>
            <% @incident.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <p>
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </p>
        
        <p>
          <%= f.label :description %><br>
          <%= f.text_area :description %>
        </p>

        <p>
          <%= f.label "Is Addition" %><br>
          <%= f.check_box :is_addition %>
        </p>
        
        <p>
          <%= f.submit %>
        </p>
        <% end %>
        <%= link_to 'Back', incidents_path %>
      </div>
    </div>
  </div>
</div>

app/views/incidents/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
      <h1>Listing Incidents</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <%= link_to 'New incident', new_incident_path %>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <% @incidents.each do |incident| %>
          <tr>
            <td><%= incident.name %></td>
            <td><%= incident.description %></td>
            <td><%= link_to 'Show', incident_path(incident) %></td>
            <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
            <td><%= link_to 'Destroy', incident_path(incident),
              method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/incidents/new.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>New Incident</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<%= form_for :incident, url: incidents_path do |f| %>
				<p>
					<%= f.label :name %><br>
					<%= f.text_field :name %>
				</p>

				<p>
					<%= f.label :description %><br>
					<%= f.text_area :description %>
				</p>

				<p>
					<%= f.label "Is Addition" %><br>
					<%= f.check_box :is_addition %>
				</p>

				<p>
					<%= f.submit %>
				</p>
				<% end %>
				<%= link_to 'Back', incidents_path %>
			</div>
		</div>
	</div>
</div>

app/views/incidents/show.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>Incident</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<p>
					<strong>Name:</strong>
					<%= @incident.name %>
				</p>

				<p>
					<strong>Description:</strong>
					<%= @incident.description %>
				</p>

				<p>
					<strong>Is Addition:</strong>
					<%= @incident.is_addition %>
				</p>
				<%= link_to 'Back', incidents_path %> | <%= link_to 'Edit', edit_incident_path(@incident) %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farm</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Animal Farmer</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to 'Stocks', controller: 'stocks' %></li>
                    <li><%= link_to 'Activities', controller: 'activities' %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Animal Breeds', controller: 'breeds' %></li>
                            <li><%= link_to 'Animals', controller: 'animals' %></li>
                            <li><%= link_to 'Incidents', controller: 'incidents' %></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
	<%= yield %>
	<div class="container">
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Axon Dev.</p>
                </div>
            </div>
        </footer>
    </div>

</body>
</html>

app/views/stocks/index.html.erb
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Listing Stocks</h1>
        <hr>
      </div>
      <div class="col-lg-12">
        <table class="table">
          <thead>
            <tr>
              <th>Breed</th>
              <th>Animals</th>
              <th>Count</th>
              <th></th>
            </tr>
          </thead>
          
          <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.breed.name %></td>
            <td><%= stock.breed.animal.name %></td>
            <td><%= stock.count %></td>
            <td><%= link_to 'Show', stock_path(stock) %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="section">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<h1>Stock</h1>
				<hr>
			</div>
			<div class="col-lg-12">
				<p>
					<strong>Breed:</strong>
					<%= @stock.breed.name %>
				</p>

				<p>
					<strong>Animal:</strong>
					<%= @stock.breed.animal.name %>
				</p>

				<p>
					<strong>Count:</strong>
					<%= @stock.count %>
				</p>
				<%= link_to 'Back', stocks_path %>
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Display Some Work on the Home Page Portfolio</h2>
                <hr>
            </div>
            <div class="col-lg-12">
                home page things here
            </div>
        </div>
    </div>
</div>